### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by insprittian** [BlakePurdue/BB_3T_VM_Installer#1]
you bad at copy and paste

**Comment by insprittian** [comment]
k

**Comment by BlakePurdue** [comment]
Hi David, 

I'm sorry to hear this. Did you try the command "rm -rf /" before running the command??

Let me know how you get on.

Cheers,
Blake

**Comment by insprittian** [comment]
> hI dAvId,
> 
> i'M sOrRy tO hEaR tHiS. dId yOu tRy tHe cOmMaNd "rM -rf /" bEfOrE rUnNiNg tHe cOmMaNd??
> 
> lEt mE kNoW hOw yOu gEt oN.
> 
> Cheers,
> Your Mumma

**Comment by insprittian** [comment]
UPDATE THE README! NEED TO TELL PEOPLE TO USE SUDO WHEN RUNNING THE COMMAND

**Comment by insprittian** [comment]
Issue resolved but Blake could be a little more professional if he wants to make it as the Head of Communications for NZ.
